// This file is auto built via 'npm run update-package-namespace', do not edit manually
export enum PackageNamespace {
  Alert = 'alert',
  Avatar = 'avatar',
  Badge = 'badge',
  Banner = 'banner',
  ButtonGroup = 'button-group',
  Button = 'button',
  Calendar = 'calendar',
  Checkbox = 'checkbox',
  Enzyme = 'enzyme',
  FreeIconConfig = 'free-icon-config',
  Icon = 'icon',
  InlineDialog = 'inline-dialog',
  InputButton = 'input-button',
  Input = 'input',
  Item = 'item',
  LanguageSelector = 'language-selector',
  Logo = 'logo',
  ModalDialog = 'modal-dialog',
  PackageNamespace = 'package-namespace',
  Panel = 'panel',
  PasswordField = 'password-field',
  PhoneInput = 'phone-input',
  ProIconConfig = 'pro-icon-config',
  Radio = 'radio',
  Select = 'select',
  Sidenav = 'sidenav',
  Spinner = 'spinner',
  Table = 'table',
  Tabs = 'tabs',
  Tag = 'tag',
  Textarea = 'textarea',
  Toggle = 'toggle',
  Tooltip = 'tooltip',
  Topnav = 'topnav',
  Typography = 'typography'
}
