name: Chromatic Base Upload

on:
  push:
    branches:
      - main
      - next

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0

      - name: Read .nvmrc
        id: nvm
        run: echo ::set-output name=nvmrc::$(cat .nvmrc)

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.nvmrc }}

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install 🔧
        run: npm ci

      - name: Build and Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: 'build'
          workingDir: system/stories
        env:
          NODE_OPTIONS: --max-old-space-size=16384
