name: Label Checker

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  check_labels:
    name: Check labels
    runs-on: ubuntu-latest
    steps:
      - uses: agilepathway/label-checker@v1.0.91
        with:
          one_of: major,minor,patch,internal
          none_of: invalid,wontfix,duplicate,question
          repo_token: ${{ secrets.GITHUB_TOKEN }}
